style/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('style_transfer/', include('style_transfer.urls', namespace='style_transfer')),
    path('style_transfer/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

style_transfer/urls.py
from django.urls import path
from style_transfer import views

app_name = 'style_transfer'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload_content, name='upload_content'),
    path('signup/', views.UserFormView, name='signup'),
    path('login/', views.login_user, name='login'),
    path('saved/', views.saved, name='saved'),
]

style_transfer/models.py
from django.db import models


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Uploadpics(models.Model):
    Contentfile = models.ImageField(upload_to='contentupload/', null=True, blank=True, verbose_name="")
    Url_field = models.CharField(max_length=100, null=True, blank=True)
    Style_num = models.IntegerField(default=1)

    class Meta:
        ordering = ["-pk"]


class Styles(models.Model):
    Style_num = models.IntegerField(default=1)
    Stylefile = models.ImageField(upload_to='stylefile/', null=True, blank=True)

style_transfer/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from .models import Uploadpics
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    # password= forms.CharField(widget= forms.PasswordInput)
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class login_form(forms.Form):
    username = forms.CharField(label='Your name', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class Upload_content_style(ModelForm):
    # url_field = forms.CharField(max_length=100)
    class Meta:
        model = Uploadpics
        fields = ['Url_field', 'Style_num', 'Contentfile']

        widgets = {
            'Url_field': forms.HiddenInput(attrs={'id': 'url_field', 'name': 'url_field'}),
            'Style_num': forms.HiddenInput(attrs={'id': 'style_num', 'name': 'style_num'}),
            'Contentfile': forms.FileInput(
                attrs={'id': 'file_in', 'style:"height=200px;"' 'name': 'file_in', 'placeholder': 'asddvef',
                       'class': 'smoothscroll btn btn--stroke'}),

        }

style_transfer/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import *
from django.contrib import messages
from .models import Styles
from style_transfer_backend import Tools, StyleTransfer2
import numpy as np
import os
from style.settings import MEDIA_ROOT, BASE_DIR


# Create your views here.

def index(request):
    return render(request, 'style_transfer/home.html', {})


def upload_content(request):
    print("here")
    # Handle file upload
    if request.method == 'POST':
        form = Upload_content_style(request.POST or None, request.FILES or None)
        print(request.FILES)
        if form.is_valid():

            # extract style path
            style_id = form.cleaned_data['Style_num']
            style_object = Styles.objects.get(Style_num=style_id)
            style_path = style_object.Stylefile.path

            # extract content image id
            instance = form.save(commit=False)
            instance.save()
            content_object = Uploadpics.objects.get(id=instance.id)
            if content_object.Url_field is None:
                content_path = content_object.Contentfile.path
            else:
                content_path = "nothing"

            content_image = Tools.load_img(content_path, True)
            style_image = Tools.load_img(style_path, True)
            output_image = StyleTransfer2.style_transfer(content_image, style_image)

            random_name = "output{x}.jpg".format(x=np.random.randn())
            img_path2 = os.path.join(BASE_DIR, 'media', 'saved_images', random_name)

            output_image.save(img_path2)
            img_path2 = '/media/' + 'saved_images/' + random_name

            request.session["path_img"] = img_path2

        return redirect("style_transfer:saved")

    else:
        form = Upload_content_style()  # A empty, unbound form
        context = {
            "form": form,
            "list": Styles.objects.all(),
        }
        return render(request, 'style_transfer/upload.html', context)


def login_user(request):
    if request.user.is_authenticated:
        logout(request)

    if request.method == 'POST':
        form = login_form(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is None:
                form1 = login_form()
                context = {
                    "form": form1,
                }
                return render(request, 'style_transfer/login.html', context)
            # print("Brook was here")
            login(request, user)
            return redirect('style_transfer:upload_content')

    form = login_form()
    context = {
        "form": form,
    }
    return render(request, 'style_transfer/login.html', context)


def UserFormView(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        print(request.POST["username"])
        if form.is_valid():
            form.save()
            return redirect("upload_content")
        print("invalid form")
        messages.error(request, "Error")
        form = UserForm()
        context = {
            "form": form,
        }
        return render(request, "style_transfer/signup.html", context)
    print("invalid post")
    form = UserForm()
    context = {
        "form": form,
    }
    return render(request, "style_transfer/signup.html", context)


def saved(request):
    context = {
        "path_img": request.session["path_img"]
    }
    return render(request, 'style_transfer/saved_img.html', context)

templates/style_transfer/home.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 9 ]>
<html class="no-js oldie" lang="en"> <![endif]-->
<!--[if IE 9 ]>
<html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Hey There, Artist!!</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href='{% static "style_transfer/css/base.css" %}'>
    <link rel="stylesheet" href='{% static "style_transfer/css/main.css" %}'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <!--   <link rel="stylesheet" href="css/vendor.css"> -->
    <!-- <link rel="stylesheet" href='{% static "style_transfer/css/main1.css" %}'> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- script
    ================================================== -->
    <script src="js/modernizr.js"></script>
    <script src="js/pace.min.js"></script>


    <style>
        div.logo img {
            position: relative;
            right: -120px;
            top: 100px;
            z-index: 10;
        }

    </style>

</head>

<body id="top">


<!-- home
================================================== -->
<nav class="navbar navbar-expand-lg navbar-dark static-top" style="background-color: rgb(59, 17, 87);">
    <a href="../index"><img src="{% static 'style_transfer/img/x1.png' %}" height="80px" width="80px" style=""></a>
    <div class="container">
        <a class="navbar-brand" href="../" style="font-size: 3em; "><strong>Art & Soul</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="../about_team" style="font-size: 2.5em; ">About Me
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="../about_project" style="font-size: 2.5em; ">About The Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="../instruction" style="font-size: 2.5em; ">Instructions</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<section id="home" class="s-home target-section" data-parallax="scroll" data-natural-width=3000 data-natural-height=2000
         data-position-y=center
         style="background-image: url('{% static "style_transfer/img/option1.png" %}');">
    <!-- <div class="overlay"></div> -->
    <div class="shadow-overlay"></div>

    <div class="home-content">

        <div class="row home-content__main" style="left: 50px; top: 0.0001%;">

            <!-- <h3>Art & Soul</h3> -->

            <h1>
                At Art & Soul,<br>
                We work towards connecting <br>
                ideas & experiences by providing<br>
                them a platform to be Artistic, <br>
                to Paint as they Think.
            </h1>
            <div class="logo">
                <img src="{% static 'style_transfer/img/x1.png' %}" height="200px" width="200px" style="">
            </div>
            <!-- <div class="home-content__buttons" style='align-content: bottom'>
                <a href="/login" class="smoothscroll btn btn--stroke">
                    Login
                </a>
                <a href="/signup" class="smoothscroll btn btn--stroke">
                    Sign Up
                </a>
            </div> -->

        </div>
        <div class="home-content__buttons">
            <a href={% url 'style_transfer:login' %} class="smoothscroll btn btn--stroke" style="text-align: center;" >
            Login
            </a>
            <a href={% url 'style_transfer:signup' %} class="smoothscroll btn btn--stroke">
            Sign Up
            </a>
        </div>

    </div> <!-- end home-content -->


    <ul class="home-social">
        <li>
            <a href="#0"><i class="fa fa-facebook" aria-hidden="true"></i><span>Facebook</span></a>
        </li>
        <li>
            <a href="#0"><i class="fa fa-twitter" aria-hidden="true"></i><span>Twiiter</span></a>
        </li>
        <li>
            <a href="#0"><i class="fa fa-instagram" aria-hidden="true"></i><span>Instagram</span></a>
        </li>
        <li>
            <a href="#0"><i class="fa fa-behance" aria-hidden="true"></i><span>Behance</span></a>
        </li>
        <li>
            <a href="#0"><i class="fa fa-dribbble" aria-hidden="true"></i><span>Dribbble</span></a>
        </li>
    </ul>
    <!-- end home-social -->

</section> <!-- end s-home -->

<!-- preloader
================================================== -->
<div id="preloader">
    <div id="loader">
        <div class="line-scale-pulse-out">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</div>


<!-- Java Script
================================================== -->
<!-- <script src="js/jquery-3.2.1.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/main.js"></script>
-->
</body>

</html>

templates/style_transfer/index.html
<!DOCTYPE html>
<html>
<head>
	<title>yayy</title>
</head>
<body>{% load static %}
<!DOCTYPE html>
<!--[if lt IE 9 ]><html class="no-js oldie" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Hey There, Artist!!</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href='{% static "style_transfer/css/base.css" %}'>
  <!--   <link rel="stylesheet" href="css/vendor.css"> -->
    <link rel="stylesheet" href='{% static "style_transfer/css/main.css" %}'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- script
    ================================================== -->
    <script src="js/modernizr.js"></script>
    <script src="js/pace.min.js"></script>

</head>

<body id="top" >

    <!-- home
    ================================================== -->
    <section id="home" class="s-home target-section" data-parallax="scroll"  data-natural-width=3000 data-natural-height=2000 data-position-y=center 
    	style="background-image: url('{% static "style_transfer/img/option3.jpeg" %}');">
        <!-- <div class="overlay"></div> -->
        <div class="shadow-overlay"></div>

        <div class="home-content">

            <div class="row home-content__main">

                <h1>Select Your Image And<br>
                The Style That You Like!</h1>

             
                <div class="home-content__buttons">
                    <a href="/upload" class="smoothscroll btn btn--stroke">
                        Upload Image
                    </a>
                    <a href="/doodle" class="smoothscroll btn btn--stroke">
                        Draw A Doodle
                    </a>
                </div>

            </div>

        </div> <!-- end home-content -->


        <ul class="home-social">
            <li>
                <a href="#0"><i class="fa fa-facebook" aria-hidden="true"></i><span>Facebook</span></a>
            </li>
            <li>
                <a href="#0"><i class="fa fa-twitter" aria-hidden="true"></i><span>Twiiter</span></a>
            </li>
            <li>
                <a href="#0"><i class="fa fa-instagram" aria-hidden="true"></i><span>Instagram</span></a>
            </li>
            <li>
                <a href="#0"><i class="fa fa-behance" aria-hidden="true"></i><span>Behance</span></a>
            </li>
            <li>
                <a href="#0"><i class="fa fa-dribbble" aria-hidden="true"></i><span>Dribbble</span></a>
            </li>
        </ul> 
        <!-- end home-social -->

    </section> <!-- end s-home -->

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader">
            <div class="line-scale-pulse-out">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>


    <!-- Java Script
    ================================================== -->
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

</body>

</html>
</body>
</html>

templates/style_transfer/login.html
{%load static%}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html><html lang='en' class=''>
<head><script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script><meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" /><link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" /><link rel="canonical" href="https://codepen.io/frytyler/pen/EGdtg" />

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style_transfer/css/tp.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css'><script src='https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js'></script>
<style class="cp-pen-styles">@import url(https://fonts.googleapis.com/css?family=Open+Sans);
.btn { display: inline-block; *display: inline; *zoom: 1; padding: 4px 10px 4px; margin-bottom: 0; font-size: 13px; line-height: 18px; color: #333333; text-align: center;text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75); vertical-align: middle; background-color: #f5f5f5; background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6); background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6)); background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6); background-image: -o-linear-gradient(top, #ffffff, #e6e6e6); background-image: linear-gradient(top, #ffffff, #e6e6e6); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#ffffff, endColorstr=#e6e6e6, GradientType=0); border-color: #e6e6e6 #e6e6e6 #e6e6e6; border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25); border: 1px solid #e6e6e6; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); cursor: pointer; *margin-left: .3em; }
.btn:hover, .btn:active, .btn.active, .btn.disabled, .btn[disabled] { background-color: #e6e6e6; }
.btn-large { padding: 9px 14px; font-size: 15px; line-height: normal; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; }
.btn:hover { color: #333333; text-decoration: none; background-color: #e6e6e6; background-position: 0 -15px; -webkit-transition: background-position 0.1s linear; -moz-transition: background-position 0.1s linear; -ms-transition: background-position 0.1s linear; -o-transition: background-position 0.1s linear; transition: background-position 0.1s linear; }
.btn-primary, .btn-primary:hover { text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25); color: #ffffff; }
.btn-primary.active { color: rgba(255, 255, 255, 0.75); }
.btn-primary { background-color: #4a77d4; background-image: -moz-linear-gradient(top, #6eb6de, #4a77d4); background-image: -ms-linear-gradient(top, #6eb6de, #4a77d4); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#6eb6de), to(#4a77d4)); background-image: -webkit-linear-gradient(top, #6eb6de, #4a77d4); background-image: -o-linear-gradient(top, #6eb6de, #4a77d4); background-image: linear-gradient(top, #6eb6de, #4a77d4); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#6eb6de, endColorstr=#4a77d4, GradientType=0);  border: 1px solid #3762bc; text-shadow: 1px 1px 1px rgba(0,0,0,0.4); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.5); }
.btn-primary:hover, .btn-primary:active, .btn-primary.active, .btn-primary.disabled, .btn-primary[disabled] { filter: none; background-color: #4a77d4; }
.btn-block { width: 100%; display:block; }

* { -webkit-box-sizing:border-box; -moz-box-sizing:border-box; -ms-box-sizing:border-box; -o-box-sizing:border-box; box-sizing:border-box; }

html { width: 100%; height:100%; overflow:hidden; }

body { 
	width: 100%;
	height:100%;
	font-family: 'Open Sans', sans-serif;
	background: #092756;
	background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
	background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
}
.login { 
	position: absolute;
	top: 50%;
	left: 50%;
	margin: -150px 0 0 -150px;
	width:300px;
	height:300px;
}
.login h1 { color: #fff; text-shadow: 0 0 10px rgba(0,0,0,0.3); letter-spacing:1px; text-align:center; }

input { 
	width: 100%; 
	margin-bottom: 10px; 
	background: rgba(0,0,0,0.3);
	border: none;
	outline: none;
	padding: 10px;
	font-size: 13px;
	color: #fff;
	text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
	border: 1px solid rgba(0,0,0,0.3);
	border-radius: 4px;
	box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
	-webkit-transition: box-shadow .5s ease;
	-moz-transition: box-shadow .5s ease;
	-o-transition: box-shadow .5s ease;
	-ms-transition: box-shadow .5s ease;
	transition: box-shadow .5s ease;
}
input:focus { box-shadow: inset 0 -5px 45px rgba(100,100,100,0.4), 0 1px 1px rgba(255,255,255,0.2); }
</style></head><body>
	<nav class="navbar navbar-expand-lg navbar-dark static-top" style="background-color: rgb(59, 17, 87);">
            <a href="../index"><img src="{% static 'style_transfer/img/x1.png' %}" height="80px" width="80px" style=""></a>
            <div class="container">
              <a class="navbar-brand" href="../" style="font-size: 3em; "><strong>Art & Soul</strong></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item ">
                    <a class="nav-link" href="../about_team" style="font-size: 1.5em; ">About Me
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="../about_project" style="font-size: 1.5em; ">About The Project</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="../instruction" style="font-size: 1.5em; ">Instructions</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>


<div class="login">
	<h1>Login</h1>
	<!-- {% block content %} -->
    <form method="post">
     	{% csrf_token %}
  	 	{{ form.as_p }}
    	
        <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
    </form>
    <!-- {% endblock %} -->
</div>
<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script >/* 

I built this login form to block the front end of most of my freelance wordpress projects during the development stage. 

This is just the HTML / CSS of it but it uses wordpress's login system. 

Nice and Simple

*/
//# sourceURL=pen.js
</script>
</body></html>

templates/style_transfer/saved_img.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
<style>
 div.whole {
  position: fixed;
  margin: 0;
  padding:0;
  width: 100%;
  height: 100%;
}	
div.whole img {
 margin-left: auto;
 margin-right: auto;
 margin-top: 5%;
 margin-bottom: 5%;
 display: block;
}

</style>
</head>
<body>
<!-- <h1>{{path_img}}</h1> -->
	<!-- <img src="\media\saved_images\out-0.16672156823739534.jpg"> -->
	<div class="whole" style="background-color:black">
	<img src="{{path_img}}" align="centre">
	</div>

</body>
</html>